export enum GenreType {
    Fiction = "Fiction",
    NonFiction = "NonFiction"  
}

export enum FictionGenre {
   Action = "Action",
   Adventure = "Adventure",
   AlternateHistory = "AlternateHistory",
   Anthology = "Anthology",
   Children = "Children",
   Classic  = "Classic ",
   ComicBook = "ComicBook",
   ComingOfAge = "ComingOfAge",
   Crime = "Crime",
   Drama = "Drama",
   Fairytale = "Fairytale",
   Fantasy = "Fantasy",
   HistoricalFiction = "HistoricalFiction",
   Horror = "Horror",
   Mystery = "Mystery",
   Paranormal = "Paranormal",
   Romance = "Romance",
   Poetry = "Poetry",
   Political = "Political",
   Satire = "Satire",
   ScienceFiction = "ScienceFiction",
   ShortStory = "ShortStory",
   Suspense = "Suspense",
   Thriller = "Thriller",
   Western = "Western",
   YoungAdult = "YoungAdult",
}

export enum NonFictionGenre {
    Art = "Art",
    Autobiography = "Autobiography",
    Biography = "Biography",
    Business = "Business",
    Crafts = "Crafts",
    Cookbook = "Cookbook",
    Diary = "Diary",
    Dictionary = "Dictionary",
    Encyclopedia = "Encyclopedia",
    Guide = "Guide",
    Health = "Health",
    History = "History",
    HomeAndGarden = "HomeAndGarden",
    Humor = "Humor",
    Journal = "Journal",
    Math = "Math",
    Memoir = "Memoir",
    Philosophy = "Philosophy",
    Prayer = "Prayer",
    Religion = "Religion",
    Textbook = "Textbook",
    TrueCrime = "TrueCrime",
    Review = "Review",
    Science = "Science",
    SelfHelp = "SelfHelp",
    Sports = "Sports",
    Travel = "Travel",
}